### ISSUE TITLE
Ignore unexisting replacements

### ISSUE THREAD

**Issue by libasoles** [Matt-Esch/string-template#20]
Hi. I'm facing a problem with React && webpack imports.
This line is being replaced even when I'm not providing a replacements in my array:

`import React, {Component} from 'react';`

Script:
```js
const replacements = {
        _singular_: 'user',
        _plural_: 'users',
        _capital_singular_: 'User',
        _capital_plural_: 'Users',
        _upper_singular_: 'USER',
        _upper_plural_: 'USERS',
    }

var formattedData = format(data, replacements);
```

So, `{Component}` should remain untouched. Or at least, please provide a flag to handle that unwanted replacements. 

Or maybe this feature is already present and it's just undocumented?

Thanks.

**Comment by Kostanos** [comment]
I think in this case better to add different key characters.

Something like:
```
format.setKey({start: '##', end: '/#});
```
so, format will use for keys like: `##myVar/#`, instead of `{myVar}`

**Comment by libasoles** [comment]
Cool, that would be enough. Thanks.

**Comment by 8acker** [comment]
Hi, I am facing same issue, is this already implemented?

**Comment by libasoles** [comment]
Hi @tbouchnafa . As Kostanos said, don't use these keys `{}`, but a different markup. That will remain your code brackets untouched.
