### ISSUE TITLE
Support '_' as part of object key names

### ISSUE THREAD

**Issue by alph486** [Matt-Esch/string-template#8]
This would be really helpful. There are some cases where third parties use _ as a separator. If I want to use those raw objects, I need to convert the keynames before I can pass them to string-template.

**Comment by ifxsoftware** [comment]
Just caught this one as well, couldnt figure out why my variables weren't working

**Comment by rw3iss** [comment]
For real.

**Comment by ashwanthkumar** [comment]
Sent PR for this at #13

**Comment by Matt-Esch** [comment]
fixed in v1.0.0

**Comment by alph486** [comment]
Thanks!
